### ISSUE TITLE
Pathfinder App sketch

### ISSUE THREAD

**Issue by adamtelles** [DIT112-V21/group-08#37]
Two main things are left for the iOS Pathfinder App:

   - Fixing the rotation such that the car can either rotate left or right depending on what is the shortest rotation.
   - A type of queue which will ensure that the car executes the commands in the correct order and doesn't skip any.
 
There is also a task related to the car relaying information about how far it's actually driven and rotated back to the app. So far everything appears to work fine without this, however it wouldn't hurt for the app to get some sort of confirmation that the car actually finished the command rather than the app just trusting that it did.

(Most recent work can be found in the Pathfinder-MQTT branch.)

**Comment by alex-nordin** [comment]
I've made some general improvements to the sketch. It now implements SmartCar instead of SimpleCar, and there's now one method that handles all the rotations. 

"Fixing the rotation such that the car can either rotate left or right depending on what is the shortest rotation."
I haven't quite figured out the math to make this work 100% of the time. I have something that works most of the time, but sometimes chooses the "long way around" so to speak.

**Comment by adamtelles** [comment]
> "Fixing the rotation such that the car can either rotate left or right depending on what is the shortest rotation."
> I haven't quite figured out the math to make this work 100% of the time. I have something that works most of the time, but sometimes chooses the "long way around" so to speak.

I think I got this part to work pretty good so we could look at combining the two later this week.

**Comment by adamtelles** [comment]
Issue resolved with pull request #43
